"""Bondi radiating metric → the non-zero metric-connection components Γ^a_bc.

Demonstrates the corrected 'explain at' design: the number of steps is driven by
the PROBLEM (here ~20 non-zero Christoffel components — the spine is identical at
every level); the level only changes how much each step is explained. An expert
problem stays a many-step problem.

Pipeline: check the tensor (det, symmetry, radiating limit) -> inverse metric ->
Christoffel formula -> the 20 components (computed by SymPy, grouped by upper
index, drill-down) -> verify by metric compatibility (∇g = 0).

Run:  python examples/bondi_christoffel.py
"""
import sys
import os
import re
import sympy as sp

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from integral_explainer import (MethodTrace, Step, Problem, Goal,  # noqa: E402
                                render_leveled, validate_qualification)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

# ---------------------------------------------------------------- the tensor
u, r, th, ph = sp.symbols("u r theta phi", real=True)
X = [u, r, th, ph]
NM = ["u", "r", "\\theta", "\\phi"]
beta = sp.Function("beta")(u, r, th)
gam = sp.Function("gamma")(u, r, th)
U = sp.Function("U")(u, r, th)
V = sp.Function("V")(u, r, th)

guu = V / r * sp.exp(2 * beta) - U**2 * r**2 * sp.exp(2 * gam)
G = sp.Matrix([
    [guu,                    sp.exp(2 * beta), U * r**2 * sp.exp(2 * gam),          0],
    [sp.exp(2 * beta),       0,                0,                                   0],
    [U * r**2 * sp.exp(2 * gam), 0,            -r**2 * sp.exp(2 * gam),             0],
    [0,                      0,                0,    -r**2 * sp.exp(-2 * gam) * sp.sin(th)**2],
])
Gi = G.inv()


def _christ(a, b, c):
    return sp.Rational(1, 2) * sum(
        Gi[a, d] * (sp.diff(G[d, c], X[b]) + sp.diff(G[d, b], X[c]) - sp.diff(G[b, c], X[d]))
        for d in range(4))


GAM = [[[sp.simplify(_christ(a, b, c)) for c in range(4)] for b in range(4)] for a in range(4)]


def _clean(expr) -> str:
    """SymPy expr -> compact LaTeX: drop (u,r,θ) args, write ∂_x f as f_{,x}."""
    s = sp.latex(expr)
    s = re.sub(r"{\\left\(u,r,\\theta \\right\)}", "", s)
    s = re.sub(r"\\frac{\\partial}{\\partial (\\theta|[ur])} (\\beta|\\gamma|U|V)",
               r"\2_{,\1}", s)
    s = re.sub(r"\\frac{\\partial}{\\partial (\\theta|[ur])}\s*(\\beta|\\gamma|U|V)",
               r"\2_{,\1}", s)
    return s


def _ii(*labels):
    """Join tensor index labels with a thin space so a Greek command never glues to the
    next symbol (the `\\phid` bug). e.g. (φ, d) -> '\\phi\\,d'."""
    return r"\,".join(labels)


def _working_latex(a, b, c, per_summand=False):
    """The FULL term-by-term derivation of one component, so a reader can verify every
    step themselves (explainer, not solver): recipe -> which inverse entries survive ->
    for each d, the actual metric entries -> each ∂ carried out on its own -> the
    assembled ½ g^{ad}(…) term -> sum over d -> simplify. Generated by SymPy.

    per_summand=True (high-school level): when a metric entry is itself a SUM, its
    derivative is split one line per summand (linearity), so nothing is taken on faith."""
    NMa, NMb, NMc = NM[a], NM[b], NM[c]
    surv = [d for d in range(4) if Gi[a, d] != 0]            # non-zero g^{a d}
    L = [rf"\Gamma^{{{NMa}}}{{}}_{{{_ii(NMb, NMc)}}}=\tfrac12\,g^{{{_ii(NMa, 'd')}}}"
         rf"\left(\partial_{{{NMb}}}\,g_{{{_ii('d', NMc)}}}+\partial_{{{NMc}}}\,g_{{{_ii('d', NMb)}}}"
         rf"-\partial_{{d}}\,g_{{{_ii(NMb, NMc)}}}\right)"]
    inv = r",\quad ".join(rf"g^{{{_ii(NMa, NM[d])}}}={_clean(Gi[a, d])}" for d in surv)
    L.append(rf"\text{{only nonzero }}g^{{{_ii(NMa, 'd')}}}:\quad {inv}")
    dterms = []
    for d in surv:
        NMd = NM[d]
        e1, e2, e3 = G[d, c], G[d, b], G[b, c]
        d1, d2, d3 = sp.diff(e1, X[b]), sp.diff(e2, X[c]), sp.diff(e3, X[d])
        L.append(rf"d={NMd}:\quad g_{{{_ii(NMd, NMc)}}}={_clean(e1)},\quad "
                 rf"g_{{{_ii(NMd, NMb)}}}={_clean(e2)},\quad g_{{{_ii(NMb, NMc)}}}={_clean(e3)}")
        if per_summand:                                     # high-school: one line per summand
            for vi, vlab, ent, loi, loj in ((b, NMb, e1, NMd, NMc),
                                            (c, NMc, e2, NMd, NMb),
                                            (d, NMd, e3, NMb, NMc)):
                lhs = rf"\partial_{{{vlab}}}\,g_{{{_ii(loi, loj)}}}"
                val = sp.diff(ent, X[vi])
                if isinstance(ent, sp.Add) and len(ent.args) > 1:
                    split = "+".join(rf"\partial_{{{vlab}}}\left({_clean(t)}\right)" for t in ent.args)
                    ev = "+".join(rf"\left({_clean(sp.diff(t, X[vi]))}\right)" for t in ent.args)
                    L.append(rf"{lhs}={split}")             # linearity: differentiate each summand
                    L.append(rf"\qquad={ev}={_clean(val)}")
                else:
                    L.append(rf"{lhs}={_clean(val)}")
        else:                                               # grad/undergrad: the three ∂ on one line
            L.append(rf"\partial_{{{NMb}}}\,g_{{{_ii(NMd, NMc)}}}={_clean(d1)},\quad "
                     rf"\partial_{{{NMc}}}\,g_{{{_ii(NMd, NMb)}}}={_clean(d2)},\quad "
                     rf"\partial_{{{NMd}}}\,g_{{{_ii(NMb, NMc)}}}={_clean(d3)}")
        bracket = d1 + d2 - d3
        term = sp.Rational(1, 2) * Gi[a, d] * bracket
        L.append(rf"\tfrac12\,g^{{{_ii(NMa, NMd)}}}\left({_clean(bracket)}\right)"
                 rf"=\tfrac12\left({_clean(Gi[a, d])}\right)\left({_clean(bracket)}\right)={_clean(sp.expand(term))}")
        dterms.append(term)
    if len(surv) > 1:
        L.append(rf"\Gamma^{{{NMa}}}{{}}_{{{_ii(NMb, NMc)}}}=\sum_d(\cdots)={_clean(sp.expand(sp.Add(*dterms)))}")
    L.append(rf"\Gamma^{{{NMa}}}{{}}_{{{_ii(NMb, NMc)}}}={_clean(GAM[a][b][c])}")
    return tuple(L)


# count + verify (metric compatibility ∇_a g_bc = 0)
NONZERO = [(a, b, c) for a in range(4) for b in range(4) for c in range(b, 4) if GAM[a][b][c] != 0]
_viol = 0
for a in range(4):
    for b in range(4):
        for c in range(4):
            e = sp.simplify(sp.diff(G[b, c], X[a]) - sum(GAM[d][a][b] * G[d, c] + GAM[d][a][c] * G[b, d] for d in range(4)))
            if e != 0:
                _viol += 1
DETG = sp.simplify(G.det())


# ---------------------------------------------------------------- the problem
def problem() -> Problem:
    return Problem(
        latex=r"ds^2=\left(\tfrac{V}{r}e^{2\beta}-U^2r^2e^{2\gamma}\right)du^2+2e^{2\beta}\,du\,dr"
              r"+2Ur^2e^{2\gamma}\,du\,d\theta-r^2\left(e^{2\gamma}d\theta^2+e^{-2\gamma}\sin^2\theta\,d\phi^2\right)",
        represents="Bondi radiating metric (axisymmetric Bondi–Sachs); β,γ,U,V free functions of (u,r,θ); "
                   "coords (u,r,θ,φ) = indices (0,1,2,3) — matching D'Inverno; a comma = ∂/∂(that coord); "
                   "signature +−−−",
        goal=Goal.EVALUATE,
        integral="the non-zero metric-connection components Γ^a_bc",
    )


def _component_steps(per_summand=False) -> list:
    """The SPINE — identical at every level. One parent per upper index a;
    each non-zero Γ^a_bc is a child (drill-down). Step count = the problem."""
    parents = []
    for a in range(4):
        kids = [Step(title=rf"$\Gamma^{{{NM[a]}}}{{}}_{{{NM[b]}{NM[c]}}}\;\;(\Gamma^{{{aa}}}{{}}_{{{b}{c}}})$",
                     math=(rf"\Gamma^{{{NM[a]}}}{{}}_{{{NM[b]}{NM[c]}}}={_clean(GAM[a][b][c])}",),
                     work=_working_latex(aa, b, c, per_summand))
                for (aa, b, c) in NONZERO if aa == a]
        label = {0: "u", 1: "r", 2: r"\theta", 3: r"\phi"}[a]
        parents.append(Step(
            title=rf"$\Gamma^{{{label}}}{{}}_{{bc}}$ — {len(kids)} non-zero component(s)",
            justification=r"all surviving components with this upper index (symmetric in $b,c$).",
            children=kids,
        ))
    return parents


_RESULT = ("{n} non-zero independent components Γ^a_bc (grouped above); verified two independent ways — a SymPy "
           "re-derivation and a component-for-component match to D'Inverno's printed answer to exercise 21.5.")


# ---- working / expert track (undergrad & graduate readers) ---------------------------
def _check_tensor_step(level: str) -> Step:
    if level == "expert":
        j = ("symmetric; det g = −r⁴e^(4β)sin²θ ≠ 0 (g⁻¹ exists); flat outgoing-EF limit at β=γ=U=0, V=r. "
             "Valid metric.")
    else:
        j = ("Confirm this is a valid metric, not a mistyped one. It is symmetric; det g = −r⁴e^(4β)sin²θ ≠ 0 "
             "(so g⁻¹ exists, which Γ needs); and at β=γ=U=0, V=r it collapses to ds²=du²+2du dr−r²dΩ² — flat "
             "space in outgoing Eddington–Finkelstein form, the correct no-radiation limit.")
    return Step(
        title="0. Check the tensor before starting",
        justification=j,
        math=(r"\det g=-r^{4}e^{4\beta}\sin^2\theta\neq 0",),
        check="symbolic",
    )


def _inverse_step(level: str) -> Step:
    return Step(
        title=r"1. Inverse metric  $g^{ab}$",
        justification="the contravariant metric (raises the first index of $\\Gamma$):",
        math=(r"g^{ur}=e^{-2\beta},\quad g^{rr}=-\tfrac{V}{r}e^{-2\beta},\quad g^{r\theta}=Ue^{-2\beta},"
              r"\quad g^{\theta\theta}=-\tfrac{e^{-2\gamma}}{r^2},\quad g^{\phi\phi}=-\tfrac{e^{2\gamma}}{r^2\sin^2\theta}",),
    )


def _formula_step(level: str) -> Step:
    j = ("Levi-Civita connection coefficients:" if level == "expert"
         else "the metric connection (Levi-Civita): half the inverse metric times a cyclic sum of metric derivatives.")
    return Step(
        title=r"2. The connection formula  $\Gamma^{a}{}_{bc}$",
        method_key="tensor",
        justification=j,
        math=(r"\Gamma^{a}{}_{bc}=\tfrac12\,g^{ad}\left(\partial_b g_{dc}+\partial_c g_{db}-\partial_d g_{bc}\right)",),
        check="symbolic",
    )


def _verify_step(level: str) -> Step:
    if level == "expert":
        j = (f"∇_a g_bc = 0 in {_viol}/64 (SymPy) and Γ symmetric in (b,c) ⇒ the unique Levi-Civita connection. "
             f"Limits: Γ^φ_θφ→cotθ, Γ^θ_rθ→1/r.")
    else:
        j = (f"The Levi-Civita connection is the UNIQUE symmetric, metric-compatible one. These Γ are "
             f"symmetric in (b,c) by construction, and ∇_a g_bc = ∂_a g_bc − Γ^d_ab g_dc − Γ^d_ac g_db "
             f"vanishes in {_viol}/64 components — i.e. all 64 hold (checked by SymPy). So they are provably "
             f"correct, not just plausible. Flat/no-shear limits also give Γ^φ_θφ→cotθ and Γ^θ_rθ→1/r.")
    return Step(
        title=f"Verify: metric compatibility  ∇_a g_bc = 0  +  textbook cross-check",
        justification=j + (" Independently, all 20 components match D'Inverno's printed answer to exercise 21.5 "
                           "component-for-component (his index map 0,1,2,3 = u,r,θ,φ)."),
        math=(r"\nabla_a g_{bc}=\partial_a g_{bc}-\Gamma^{d}{}_{ab}g_{dc}-\Gamma^{d}{}_{ac}g_{bd}=0",),
        references=("D'Inverno, Introducing Einstein's Relativity — Answer to exercise 21.5 (pp. 368–369): "
                    "all 20 non-zero independent Γ agree exactly.",),
        check="symbolic",
    )


# ---- plain / HIGH-SCHOOL track: built from genuine high-school knowledge --------------
# Rule 7: every step must land for a high-schooler (Pythagoras, basic calculus, functions).
# No "metric/tensor/Levi-Civita/Eddington-Finkelstein" assumed — each is built or avoided.
def _plain_intro_step() -> Step:
    return Step(
        title="0. What is this formula? (a recipe for distance)",
        justification=(r"The first line, $ds^2=\dots$, is a recipe for distance: it gives the squared length of one "
                       r"tiny step. On flat paper that recipe is just Pythagoras, $ds^2=dx^2+dy^2$. In the space and "
                       r"time around a star that is radiating it picks up extra factors and a couple of cross-terms — "
                       r"and that is all this big formula is. The four letters $u,r,\theta,\phi$ are coordinates: "
                       r"labels for where and when you are ($r$ is distance outward, $\theta,\phi$ are angles, $u$ is "
                       r"a kind of time). The functions $\beta,\gamma,U,V$ are dials saying how stretched space is at "
                       r"each point. (Quick sanity check: turn the dials off and the recipe becomes ordinary flat "
                       r"space, so it holds together.) Our task: measure how this stretched grid bends."),
        math=(r"\text{flat (Pythagoras): }\ ds^2=dx^2+dy^2",),
    )


def _plain_whatis_step() -> Step:
    return Step(
        title="1. What we are actually finding (how the grid bends)",
        justification=(r"Draw a grid on a curved or stretched surface and the lines do not stay evenly spaced or "
                       r"straight — they bend and fan out. (Think of the lines of longitude on a globe crowding "
                       r"together near the poles.) The connection, written $\Gamma$, is a set of numbers that measures "
                       r"exactly that bending: how much one grid direction tips as you move along another. There is "
                       r"one number for each combination of (which direction tips, toward which, as you move which "
                       r"way). The question asks for all of them that are not zero."),
    )


def _plain_formula_step() -> Step:
    return Step(
        title=r"2. The recipe for each bending-number $\Gamma^{a}{}_{bc}$",
        justification=(r"There is a standard recipe for each bending-number $\Gamma^{a}{}_{bc}$. In words: take how "
                       r"fast the distance-recipe's factors change as you move — the symbol $\partial$ just means "
                       r"'rate of change' (a derivative) — combine them in a fixed pattern, and multiply by the "
                       r"metric's 'undo' numbers $g^{ad}$ (next step). A first course uses the recipe without proving "
                       r"it; notice it needs only derivatives and algebra."),
        math=(r"\Gamma^{a}{}_{bc}=\tfrac12\,g^{ad}\left(\partial_b g_{dc}+\partial_c g_{db}-\partial_d g_{bc}\right)",),
    )


def _plain_inverse_step() -> Step:
    return Step(
        title=r"3. The 'undo' numbers $g^{ab}$ (the inverse)",
        justification=(r"Before the recipe we need the metric's undo numbers $g^{ab}$ — the inverse, the way "
                       r"$\tfrac13$ undoes multiplying by $3$. For this space they come out short:"),
        math=(r"g^{ur}=e^{-2\beta},\quad g^{rr}=-\tfrac{V}{r}e^{-2\beta},\quad g^{r\theta}=Ue^{-2\beta},"
              r"\quad g^{\theta\theta}=-\tfrac{e^{-2\gamma}}{r^2},\quad g^{\phi\phi}=-\tfrac{e^{2\gamma}}{r^2\sin^2\theta}",),
    )


def _plain_worked_step() -> Step:
    return Step(
        title=r"4. One bending-number worked out in full: $\Gamma^{\phi}{}_{\theta\phi}=\cot\theta-\gamma_{,\theta}$",
        justification=(r"Let us do one all the way — the tidiest. For the $\phi$ direction the recipe collapses to a "
                       r"single piece: half the undo-number $g^{\phi\phi}$ times the rate of change of $g_{\phi\phi}$ "
                       r"as the angle $\theta$ changes. Here $g_{\phi\phi}=-r^2e^{-2\gamma}\sin^2\theta$. The only "
                       r"part that moves with $\theta$ is $\sin^2\theta$, whose rate of change is "
                       r"$2\sin\theta\cos\theta$ — the piece that becomes $\cot\theta$ — plus a small bit from the "
                       r"dial $\gamma$. Multiply by $\tfrac12 g^{\phi\phi}$ and everything cancels to "
                       r"$\cot\theta-\gamma_{,\theta}$."),
        math=(r"\Gamma^{\phi}{}_{\theta\phi}=\tfrac12\,g^{\phi\phi}\,\partial_\theta g_{\phi\phi}"
              r"=\tfrac12\!\left(-\frac{e^{2\gamma}}{r^{2}\sin^2\theta}\right)\partial_\theta\!\left(-r^{2}e^{-2\gamma}\sin^2\theta\right)"
              r"=\cot\theta-\gamma_{,\theta}",),
        detail="rate of change of (−r²e^(−2γ)sin²θ) in θ = −r²e^(−2γ)(2 sinθ cosθ − 2γ_,θ sin²θ);"
               "  times ½ g^φφ  →  cotθ − γ_,θ.",
    )


def _plain_ceiling_step() -> Step:
    return Step(
        title="5. The full answer — and an honest word on it",
        justification=(r"Below are all 20 bending-numbers that are not zero. The short ones you can now read straight "
                       r"off — e.g. $\Gamma^{r}{}_{rr}=2\beta_{,r}$ (just twice the rate of change of the dial $\beta$ "
                       r"in the $r$ direction), or the $\cot\theta-\gamma_{,\theta}$ we just found. The long ones run "
                       r"to a dozen terms each: they come from turning the very same handle with far more bookkeeping, "
                       r"and reading them term-by-term is genuinely past a first course. That is the honest ceiling — "
                       r"at this level the win is seeing where they come from and that they check out, not grinding "
                       r"through every term."),
    )


def _plain_verify_step() -> Step:
    return Step(
        title="6. How do we know it is right?",
        justification=(r"Two independent checks. First, a computer algebra system re-derived all 20 from scratch and "
                       r"got the same answer. Second — the real confidence — they match, line for line, the printed "
                       r"answers in a published textbook (D'Inverno, exercise 21.5). When your own working and an "
                       r"established textbook agree on all 20, you can trust the result."),
        references=("D'Inverno, Introducing Einstein's Relativity — Answer to exercise 21.5 (pp. 368–369): "
                    "all 20 non-zero independent Γ agree exactly.",),
    )


def _why_step(level: str) -> Step:
    if level == "plain":
        return Step(
            title="Why this plan — spot the standard recipe",
            justification=(r"The question gives a 'distance recipe' and asks how its grid bends. There is a single "
                           r"standard recipe for that bending (the next section). So the whole plan is: recognise "
                           r"this is that standard thing, then turn the handle with algebra — exactly, not with "
                           r"numbers. (Numbers would hide where each piece comes from, and we could not check them "
                           r"against a textbook.)"),
        )
    j = (r"the 'metric connection' is, by definition, the Levi-Civita connection — the unique symmetric, "
         r"metric-compatible connection — so the method is forced: apply its closed-form coefficients symbolically."
         if level == "expert" else
         r"the metric connection of any metric is the Levi-Civita connection: one standard formula, built from the "
         r"metric. We recognise the object and apply that formula, keeping $\beta,\gamma,U,V$ exact.")
    return Step(
        title="Why this approach — it is the Levi-Civita connection",
        method_key="tensor",
        justification=j,
        forced_by=r"the object asked for — the metric connection — is uniquely fixed by the metric (fundamental "
                  r"theorem of Riemannian geometry); there is nothing to choose.",
        payoff=r"a closed form keeps every $\beta,\gamma,U,V$ exact, so the result carries the geometry and can be "
               r"checked term-by-term against the textbook; a numeric grid would destroy that.",
        relies_on=r"the metric being non-degenerate so $g^{-1}$ exists — confirmed in the first step.",
    )


def _add(t: MethodTrace, step: Step, section: str) -> None:
    step.section = section
    t.add(step)


def _build_plain() -> MethodTrace:
    t = MethodTrace.from_problem(problem())
    _add(t, _plain_intro_step(), "why")          # WHY: what this is, what we're finding, the plan
    _add(t, _plain_whatis_step(), "why")
    _add(t, _why_step("plain"), "why")
    _add(t, _plain_formula_step(), "how")        # HOW: the recipe and the undo-numbers
    _add(t, _plain_inverse_step(), "how")
    _add(t, _plain_worked_step(), "step")        # STEPS: one in full, then all, then the check
    _add(t, _plain_ceiling_step(), "step")
    for s in _component_steps(per_summand=True):    # high-school: split each ∂ per summand
        _add(t, s, "step")
    _add(t, _plain_verify_step(), "step")
    t.result = _RESULT.format(n=len(NONZERO))
    return t


def _build(level: str) -> MethodTrace:
    if level == "plain":
        return _build_plain()
    t = MethodTrace.from_problem(problem())
    _add(t, _why_step(level), "why")             # WHY: recognise the Levi-Civita connection
    if level != "expert":                        # a grad knows the connection formula — fold it
        _add(t, _formula_step(level), "how")     # HOW: the formula (working/plain) ...
    _add(t, _inverse_step(level), "how")         #      ... and the inverse metric (all levels)
    _add(t, _check_tensor_step(level), "step")   # STEPS: check input, compute, verify
    for s in _component_steps():
        _add(t, s, "step")
    _add(t, _verify_step(level), "step")
    t.result = _RESULT.format(n=len(NONZERO))
    return t


def main() -> None:
    tracks = {"expert": _build("expert"), "working": _build("working"), "plain": _build("plain")}
    print(f"non-zero independent Γ^a_bc: {len(NONZERO)}   (∇g violations: {_viol}/64)")
    print("steps per level:", {k: len(v.steps) for k, v in tracks.items()})
    qwarn = validate_qualification(tracks)         # rule 7: bands, varying counts, every step in reach
    print("  breakdown:", "OK (bands + emergent counts + every step in reach)" if not qwarn else qwarn)
    assert not qwarn, qwarn
    out = os.path.join(os.path.dirname(__file__), "bondi_output")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "trace.html"), "w", encoding="utf-8") as f:
        f.write(render_leveled(tracks))
    with open(os.path.join(out, "trace.md"), "w", encoding="utf-8") as f:
        f.write("# Bondi metric — Christoffel symbols, three levels\n\n" + "\n\n---\n\n".join(
            f"## {lvl} ({len(tr.steps)} steps)\n\n{tr.render_markdown()}" for lvl, tr in tracks.items()))
    print(f"written to {out}")


if __name__ == "__main__":
    main()
